# Generated by Django 5.0.2 on 2024-04-09 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findmytrip', '0002_activity_flight_hotel_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_price',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='flight',
            name='flight_price',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_price',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
