# Generated by Django 5.0.2 on 2024-02-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findmytrip', '0002_activity_flight_hotel_remove_flights_package_ptr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='activity_info',
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='booking',
            name='flight_info',
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='booking',
            name='hotel_info',
            field=models.JSONField(default={}),
        ),
    ]
