# Generated by Django 5.0.2 on 2024-02-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findmytrip', '0003_booking_activity_info_booking_flight_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='activity_info',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='booking',
            name='flight_info',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='booking',
            name='hotel_info',
            field=models.JSONField(default=dict),
        ),
    ]
