# Generated by Django 5.0.2 on 2024-02-29 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findmytrip', '0004_alter_booking_activity_info_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ['flight_number']},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ['name']},
        ),
    ]
