# Generated by Django 5.0.1 on 2024-04-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findmytrip', '0004_alter_activity_activity_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='image',
            field=models.ImageField(blank=True, default='default_image.jpg', upload_to='media/'),
        ),
    ]
