# Generated by Django 5.0.1 on 2024-04-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findmytrip', '0005_alter_package_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='created_by',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
