# Generated by Django 5.0.2 on 2024-03-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findmytrip', '0007_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='activity_info',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='flight_info',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='hotel_info',
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_info',
            field=models.JSONField(default=dict),
        ),
    ]
