# Generated by Django 5.0.1 on 2024-03-28 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findmytrip', '0011_alter_package_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='agent',
        ),
        migrations.AddField(
            model_name='package',
            name='description',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='package',
            name='image',
            field=models.ImageField(blank=True, default='media/default_image.jpg', upload_to=''),
        ),
    ]
