# Generated by Django 5.0.1 on 2024-03-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findmytrip', '0013_remove_package_activities_remove_package_flights_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='activities',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='package',
            name='flights',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='package',
            name='hotels',
            field=models.JSONField(default=list),
        ),
    ]
