# Generated by Django 5.0.1 on 2024-03-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findmytrip', '0014_alter_package_activities_alter_package_flights_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='package',
            name='flights',
        ),
        migrations.RemoveField(
            model_name='package',
            name='hotels',
        ),
        migrations.AddField(
            model_name='package',
            name='activities',
            field=models.ManyToManyField(to='findmytrip.activity'),
        ),
        migrations.AddField(
            model_name='package',
            name='flights',
            field=models.ManyToManyField(to='findmytrip.flight'),
        ),
        migrations.AddField(
            model_name='package',
            name='hotels',
            field=models.ManyToManyField(to='findmytrip.hotel'),
        ),
    ]
