# Generated by Django 5.0.3 on 2024-04-06 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findmytrip', '0009_remove_package_agent_package_description_and_more'),
        ('findmytrip', '0017_alter_package_image'),
    ]

    operations = [
    ]
